<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Playlist', 'doctrine');

/**
 * BasePlaylist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $scan_id
 * @property string $service_name
 * @property string $service_unique_id
 * @property string $name
 * @property integer $mtime
 * 
 * @method integer  getId()                Returns the current record's "id" value
 * @method integer  getScanId()            Returns the current record's "scan_id" value
 * @method string   getServiceName()       Returns the current record's "service_name" value
 * @method string   getServiceUniqueId()   Returns the current record's "service_unique_id" value
 * @method string   getName()              Returns the current record's "name" value
 * @method integer  getMtime()             Returns the current record's "mtime" value
 * @method Playlist setId()                Sets the current record's "id" value
 * @method Playlist setScanId()            Sets the current record's "scan_id" value
 * @method Playlist setServiceName()       Sets the current record's "service_name" value
 * @method Playlist setServiceUniqueId()   Sets the current record's "service_unique_id" value
 * @method Playlist setName()              Sets the current record's "name" value
 * @method Playlist setMtime()             Sets the current record's "mtime" value
 * 
 * @package    streeme
 * @subpackage model
 * @author     Richard Hoar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlaylist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('playlist');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('scan_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('service_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('service_unique_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mtime', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}