<?php

/**
 * EchonestPropertiesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EchonestPropertiesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EchonestPropertiesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EchonestProperties');
    }
}