<?php

/**
 * PlaylistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaylistTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PlaylistTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Playlist');
  }
  
  /**
   * Add a playlist 
   * @param name        str: new playlist name 
   * @return            int: insert row id
   */
  public function addPlaylist( $name )
  {
    $playlist = new Playlist();
    $playlist->name = $name;
    $playlist->save();
    $id = $playlist->getId();
    $playlist->free();
    return $id;
  }
  
  /**
   * Delete a playlist 
   * @param playlist_id int: playlist id 
   * @return            int: number of rows affected
   */
  public function deletePlaylist( $playlist_id )
  {
    //delete playlist entry
    $qp = Doctrine_Query::create()
      ->delete( 'Playlist p' )
      ->where( 'p.id = ?', $playlist_id )
      ->execute();
      
    //delete associated playlist files  
    $qpf = Doctrine_Query::create()
      ->delete( 'PlaylistFiles pf' )
      ->where( 'pf.playlist_id = ?', $playlist_id  )
      ->execute();
    return ( $qp + $qpf );
  }
    
  /**
   * Fetch the playlist list
   * @param alpha str: the alphabetical grouping 
   * @return      array: of all genre entries
   */
  public function getList( $alpha = 'all' )
  {
    $q = Doctrine_Query::create()
      ->select( 'p.id, p.name' )
      ->from( 'Playlist p' );
    if( $alpha !== 'all' )
    {
      $q->where( 'upper( p.name ) LIKE ?', strtoupper( substr( $alpha, 0, 1 ) ) . '%' );
    }
    $q->orderBy( 'p.name ASC' );
    return $q->fetchArray();
  }
}